# Generated by Django 2.1.1 on 2018-09-16 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
